apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
  labels:
    app: health-api
  annotations:
    author: Francisco Santana
    app-version: 1.0.0
spec:
  replicas : 1    
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
     containers:
     - name: health-container
       image: franciscoasantana/health-e-med:v2.0
       ports:
       - containerPort: 8080
       livenessProbe:
         httpGet:
           path: /health
           port: 8080
         initialDelaySeconds: 5
         periodSeconds: 10
         failureThreshold: 3
         successThreshold: 1
         timeoutSeconds: 2
       volumeMounts:
            - name: dataprotect-keys-volume
              mountPath: /home/app/.aspnet/DataProtection-Keys
     volumes:
        - name: dataprotect-keys-volume
          emptyDir: {}