apiVersion: v1
kind: Service
metadata:
  labels:
    app: health
  name: health-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: health-api
  type: NodePort