apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-protection-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:\Projetos\Fiap\health-e-med\data
