apiVersion: v1
kind: PersistentVolume
metadata:
  name: health-pv-sql
  labels:
    name: health-pv-sql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:\Projetos\Fiap\Contato\data
    type: Directory