apiVersion: v1
kind: PersistentVolume
metadata:
  name: health-pv-sql
  labels:
    name: health-pv-sql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:\Projetos\Fiap\health-e-med\data