apiVersion: v1
kind: Pod
metadata:
  name: sqlserver-pod
  labels:
    app: sqlserver-pod
  annotations:
    author: Francisco Santana
    app-version: 1.0.0
spec:
  containers:
    - name: sqlserverpod
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - containerPort: 1433
      volumeMounts:
        - name: shared
          mountPath: /data/db
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: MSSQL_SA_PASSWORD
          value: "1q2w3e4r@#$"
  volume:
    - name: shared
      persistentVolumeClaim:
        claimName: contato-pvc